### ISSUE TITLE
Clever Serve + CleverORM issues

### ISSUE THREAD

**Issue by advancedits** [CleverStack/cleverstack-cli#58]
I have installed cleverstack with clever init myapp
Everything was installed with no errors.

Then when run "clever serve" I get the following response:
-------------------------------------------------------------------------------------
Running "clean:server" (clean) task

Running "connect:livereload" (connect) task
Started connect web server on 0.0.0.0:9000.

Running "connect:dist" (connect) task
Started connect web server on 0.0.0.0:9009.

Running "concurrent:watch" (concurrent) task
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'utils'
Warning: Task "server:web" not found. Use --force to continue.

Aborted due to warnings.
Running "watch:less" (watch) task
Running "watch:livereload" (watch) task
Waiting...Waiting...

-------------------------------------------------------------------------------------

The app seems to run fine but not sure why Gruntfile.js can't find 'utils', I checked out the file (which I had not touched) and the path looked correct to utils. The demo app seems to run fine with that error. Any ideas here?

Then I tried to install clever-orm by running the command "clever install clever-orm" in my main app folder and I get the following error:
-------------------------------------------------------------------------------------
Attempting to install clever-orm...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ? Installing clever-orm...
  ├── Installing NPM modules for clever-orm...
?    Successfully installed clever-orm...
  ├── Installing bundledDependencies...
  ├── ? Running grunt tasks for module clever-orm...
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'utils'
Warning: Task "prompt:cleverOrmConfig" not found. Use --force to continue.

Aborted due to warnings.
Running database migrations...
Error: Command failed: 'NODE_ENV' is not recognized as an internal or external c
ommand,
operable program or batch file.

-----------------------------------------------------------------------------------------

Any ideas here? 

My plan is to use SQLite with clever but having a hard time getting the demo app off the ground

**Comment by advancedits** [comment]
Just to add I'm running this in Windows command prompt

**Comment by pilsy** [comment]
Hi @advancedits, i'm taking a look at this now but i don't have a windows machine here i can test with - do you mind screen sharing to debug?

**Comment by advancedits** [comment]
yes I can screenshare for debugging....how do we start?

**Comment by advancedits** [comment]
@pilsy  let me know what screenshots you want or how you want to screenshare

**Comment by pilsy** [comment]
It would be awesome if we could organise a time to do a google hangout? email me richard.gustin86@gmail.com

**Comment by albertStaalburger** [comment]
Has this been fixed? I am having the same problem with serving the clean install. The frontend runs but the backend is giving me problems.

**Comment by advancedits** [comment]
Unfortunately no...we have decided to experiment with some other frameworks

**Comment by pilsy** [comment]
@albertStaalburger are you also running on windows?

**Comment by albertStaalburger** [comment]
Yes, I am also on Win. I traced the error and am working on finding a hot fix. I have used clever stack before but on MAC.
It looks like the utils folder is missing. It is required by jsonlint.js
var utils = require('utils');

**Comment by albertStaalburger** [comment]
Ok, so spending some time tracing the origin of the problem I see that in the *magicModule.js* the *getModulePaths()* function returns an empty array. I assume this should return an array of utilities? 
But this is the furthest I have come and seem to be running out of skills to solve this :)

Any help or guidance will be greatly appreciated.

**Comment by pilsy** [comment]
Hey @albertStaalburger - wondering if the issues you were experiencing with CleverStack were fixed along with [feat(magicModules): Added recursive folder loading, fixes #111](https://github.com/CleverStack/node-seed/commit/1af5efb4f3c62d2099ff51c59cc396e1338d37a6) ?

**Comment by albertStaalburger** [comment]
I will have a look during next week as I find time. Thank you for getting back. Will give you feedback ass soon as I have tried it.
