### ISSUE TITLE
clever install clever-orm fails

### ISSUE THREAD

**Issue by g1205610** [CleverStack/cleverstack-cli#68]
$ node --version
v0.10.38
$ cd test001038/backend/modules/
$ clever install clever-orm
Attempting to install clever-orm...
✔      Found CleverStack Backend (node-seed) in /Users/xxx/test001038/backend...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-orm...
  ├── Installing NPM modules for clever-orm...
✔    Successfully installed clever-orm...
  ├── Installing module peerDependencies...
  ├── ⚠ Running grunt tasks for module clever-orm...
ReferenceError: runTask is not defined

**Comment by pilsy** [comment]
What version of the cleverstack cli? `clever -V`

**Comment by g1205610** [comment]
It's version 1.2.6, current from npm.

**Comment by pilsy** [comment]
I believe i have fixed the issues in [Release 1.2.7](https://github.com/CleverStack/cleverstack-cli/releases/tag/1.2.7) - can you please run `npm install -g cleverstack-cli` and try again?

Also, if your running that on linux/mac then you may need to use sudo

**Comment by g1205610** [comment]
Node is installed in ~/node, so no sudo is required.
Fix confirmed! Thanks for your effort.
