### ISSUE TITLE
clever install clever-odm fails

### ISSUE THREAD

**Issue by g1205610** [CleverStack/cleverstack-cli#69]
$ node --version
v0.10.38
$ cd test001038/backend/modules/
$ clever install clever-odm
Attempting to install clever-odm...
✔      Found CleverStack Backend (node-seed) in /Users/xxx/test001038/backend...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-odm...
  ├── Installing NPM modules for clever-odm...
✔    Successfully installed clever-odm...
  ├── Installing module peerDependencies...
  ├── ⚠ Running grunt tasks for module clever-odm...
ReferenceError: runTask is not defined

**Comment by pilsy** [comment]
I believe i have fixed the issues in [Release 1.2.7](https://github.com/CleverStack/cleverstack-cli/releases/tag/1.2.7) - can you please run `npm install -g cleverstack-cli` and try again?  (if your running that on linux/mac then you may need to use sudo)

**Comment by g1205610** [comment]
Node is installed in ~/node, so no sudo is required.
Fix confirmed! Thanks for your effort.
