### ISSUE TITLE
CLI Init Issue (freezes)

### ISSUE THREAD

**Issue by scfox** [CleverStack/cleverstack-cli#75]
I am having identical issue to CLI Init errors #65, but on clever version 1.2.7

clever init cs12 -f 
freezes at either 7% or 21% of backend installation.  I've tried:
bower cache clean
npm cache clean
sudo rm -rf ~/.npm
I've also tried running clever command with sudo and reinstalling clever, bower, and npm.
All same results:

Preparing for installation...
└── Creating project installation path...

Installing Backend...
├── Installation path is .../cs12/backend...ding... ┊ Step Time: 1s ┊Downloading and extracting node-seed...

Status @ 3s | Installation Progress: [▒---------] 7 % ┊ Installing: Backend ┊ Step: Downloading and extracting node-seed... ┊ Step Time: 2s ┊

**Comment by pilsy** [comment]
Hi @scfox - i'm wondering if this is a symptom of https://github.com/derrickpelletier/node-status/issues/9#issuecomment-104736810 ...

While it's running and looks frozen, have you tried pushing the up or down key, or pressing enter ... does the output change then?

**Comment by scfox** [comment]
That did work around the problem and let it run to completion.  Thanks.
