### ISSUE TITLE
error clever init

### ISSUE THREAD

**Issue by josepe36** [CleverStack/cleverstack-cli#76]
Hello

i just discovered cleverstack and i m lock on the getting started.
My system is Ubuntu 14.04, nodejs version is v0.10.25 and npm version is 1.3.10.

Thanks

clever init CleverApp

Installing Frontend...
  ├── Installation path is /home/dev/CleverApp/frontend...
  ├── Downloading and extracting angular-seed...
  ├── Installing NPM modules...
  ├── Installing bundled modules...
  ├── Installing bower components...ess: [▒▒▒▒▒-----]  50 %   ┊   Installing: Frontend   ┊   Step: Installing NPM modules...   ┊   Step Time: 30s   ┊                                                                                          
  ├── Installing bower components for cs_messenger...
  ├── Installing bower components for cs_modal...---]  64 %   ┊   Installing: Frontend   ┊   Step: Installing bower components...   ┊   Step Time: 12s   ┊                                                                                     
  ├── Installing bower components for cs_table...
  └──Installing protractor...
Error: Command failed: npm ERR! weird error 3
npm WARN This failure might be due to the use of legacy binary "node"talling: Frontend   ┊   Step: Installing protractor (this might take awhile)...   ┊   Step Time: 6s   ┊                                                                   
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

Error: Command failed: npm ERR! weird error 3
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
From previous event:
    at /usr/local/lib/node_modules/cleverstack-cli/bin/clever-init:356:18
    at process._tickCallback (node.js:415:13)
From previous event:
    at /usr/local/lib/node_modules/cleverstack-cli/bin/clever-init:353:10
    at /usr/local/lib/node_modules/cleverstack-cli/node_modules/mkdirp/index.js:30:20
    at Object.oncomplete (fs.js:107:15)

**Comment by pilsy** [comment]
Hi @josepe36 

This looks like the protractor part of the setup is failing - to confirm can you try running `clever setup -S`? if this is the issue then everything except running the E2E tests should work ... ie `clever serve`

**Comment by josepe36** [comment]
Hi thanks
i ve not time to look at now, i ll do this laterr.

Thanks o lots

2015-06-23 6:27 GMT+02:00 Richard <notifications@github.com>:

> Hi @josepe36 <https://github.com/josepe36>
>
> This looks like the protractor part of the setup is failing - to confirm
> can you try running clever setup -S? if this is the issue then everything
> except running the E2E tests should work ... ie clever serve
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CleverStack/cleverstack-cli/issues/76#issuecomment-114350893>
> .
>



-- 
Olivier from Hybryde Team

**Comment by Ins87** [comment]
Hi,
I have the same issue, and I can confirm, setup works with `clever setup -S`, but after that with `clever serve` I got a grunt error:

`d:\myCleverApp>clever serve
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'utils'
Warning: Task "server" not found. Use --force to continue.

Aborted due to warnings.
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'utils'
Warning: Task "server:web" not found. Use --force to continue.

Aborted due to warnings.`

node v0.12.6
npm 2.11.2

**Comment by pilsy** [comment]
hey @Ins87, for the latest angular-seed you need to set your NODE_PATH - see http://cleverstack.io/documentation/backend/#setting-your-node-path for more information.

The reason for this is the "lib" and "config" folders in (now both) the front end and back end seed's - give that a try and let me know if that fixes it :+1:

**Comment by Ins87** [comment]
Hi @pilsy , you were right. Sorry, I missed that part. 
Now it's working, and also the protractor error disappears after setting the NODE_PATH

Thanks!
