### ISSUE TITLE
clever init error

### ISSUE THREAD

**Issue by TWKDreamState** [CleverStack/cleverstack-cli#77]
I have checked through all issues and I don't think I've found a similar problem.

I am using Windows 8.1 x64, Node 0.12 and the latest cleverstack-cli. I've read the issue related to Node 0.12 but this does not seem to relate to my error.

All the init is going fine until the protractor part, which is failing at the following stage ...

agnular-seed@1.2.0-rc-2 setup-protractor: 'grunt webdriver:update'.

Any ideas why this is failing for me?

Many thanks.

Debug log is as follows (with my name replaced with 'username')....

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'setup-protractor' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose run-script [ 'presetup-protractor',
5 verbose run-script   'setup-protractor',
5 verbose run-script   'postsetup-protractor' ]
6 info presetup-protractor angular-seed@1.2.0-rc-2
7 info setup-protractor angular-seed@1.2.0-rc-2
8 verbose unsafe-perm in lifecycle true
9 info angular-seed@1.2.0-rc-2 Failed to exec setup-protractor script
10 verbose stack Error: angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
10 verbose stack Exit status 3
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid angular-seed@1.2.0-rc-2
12 verbose cwd c:\Users\username\Documents\clevertest\frontend
13 error Windows_NT 6.3.9600
14 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "setup-protractor"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
18 error Exit status 3
19 error Failed at the angular-seed@1.2.0-rc-2 setup-protractor script 'grunt webdriver:update'.
19 error This is most likely a problem with the angular-seed package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     grunt webdriver:update
19 error You can get their info via:
19 error     npm owner ls angular-seed
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

And this didn't seem to be included in the log if it helps?

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\username\Documents\clevertest\frontend\npm-debug.log

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
From previous event:
    at C:\Users\username\AppData\Roaming\npm\node_modules\cleverstack-cli\bin\cle
ver-init:356:18
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at C:\Users\username\AppData\Roaming\npm\node_modules\cleverstack-cli\bin\cle
ver-init:353:10
    at C:\Users\username\AppData\Roaming\npm\node_modules\cleverstack-cli\node_mo
dules\mkdirp\index.js:30:20
    at FSReqWrap.oncomplete (fs.js:95:15)

Have also tried to downgrade to Node 0.10 but still the same error.

**Comment by pilsy** [comment]
Please take a look at https://github.com/CleverStack/cleverstack-cli/issues/76#issuecomment-121777570 for the fix for this issue.
