### ISSUE TITLE
generate new project error.

### ISSUE THREAD

**Issue by thinksource** [CleverStack/cleverstack-cli#78]
Error message for my nodejs, I think you left some modules in package.json file

Errror message:

Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'utils'
Warning: Task "webdriver:update" not found. Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "setup-protractor"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the angular-seed@1.2.0-rc-2 setup-protractor script 'grunt we
bdriver:update'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt webdriver:update
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\git\myapp\frontend\npm-debug.log

**Comment by pilsy** [comment]
See https://github.com/CleverStack/cleverstack-cli/issues/76#issuecomment-121777570
